### ISSUE TITLE
PlotMRF_hm_cont is no longer available in the new version. How does the included feature of plotMRF_hm_cont work in the new version?

### ISSUE THREAD

**Issue by Hanqingpeng** [nicholasjclark/MRFcov#27]
PlotMRF_hm_cont is no longer available in the new version. How does the included feature of plotMRF_hm_cont work in the new version?

For example: How do You Figure 1.B Predicted Interactions at Varying Zosterops Relative Abundance in Clark et al 2018？

**Comment by nicholasjclark** [comment]
Thank you for the question. The original plotMRF_hm_cont function was a little too specialised for inclusion in a package as it was designed just to be a figure for the publication and it contains dependencies that could break more easily. However you can still produce that figure and similar ones by using the original function, which is found in the utilities of MRFcov ([https://github.com/nicholasjclark/MRFcov/blob/master/R/utils.R])
